INSERT INTO stores (nom) VALUES
('Walmart'),
('Costco'),
('Target'),
('IKEA'),
('Aldi'),
('Lidl'),
('Tesco'),
('Carrefour'),
('Best Buy'),
('Home Depot'),
('7-Eleven'),
('Whole Foods Market'),
('Trader Joe''s'),
('Kroger'),
('Walgreens'),
('CVS Pharmacy'),
('Dollar General'),
('Sam''s Club'),
('Metro'),
('Auchan');

INSERT INTO items (store_id, nom, unitats)
WITH llistat(nom) AS (VALUES 
('Milk'),
('Eggs'),
('Bread'),
('Butter'),
('Cheese'),
('Apples'),
('Bananas'),
('Oranges'),
('Chicken Breast'),
('Beef Steak'),
('Rice'),
('Pasta'),
('Olive Oil'),
('Cereal'),
('Coffee'),
('Tea'),
('Toothpaste'),
('Shampoo'),
('Soap'),
('Laundry Detergent'),
('Paper Towels'),
('Toilet Paper'),
('Batteries'),
('Light Bulbs'),
('Water Bottle'),
('Chocolate'),
('Cookies'),
('Ice Cream'),
('Yogurt'),
('Juice'),
('Soda'),
('Beer'),
('Wine'),
('Flour'),
('Sugar'),
('Salt'),
('Pepper'),
('Tomato Sauce'),
('Ketchup'),
('Mustard'),
('Mayonnaise'),
('Chips'),
('Nuts'),
('Energy Drink'),
('Frozen Pizza'),
('Frozen Vegetables'),
('Fish Fillets'),
('Shrimp'),
('Toilet Cleaner'),
('Dish Soap'),
('Sponges'),
('Laundry Softener'),
('Trash Bags'),
('Tissues'),
('Deodorant'),
('Body Lotion'),
('Razor Blades'),
('Hand Sanitizer'),
('Pain Reliever'),
('Vitamins'),
('Face Mask'),
('Hand Cream'),
('Hair Conditioner'),
('Body Wash'),
('Printer Paper'),
('Notebooks'),
('Pens'),
('Markers'),
('Scissors'),
('Tape'),
('Glue'),
('Light Switch'),
('Extension Cord'),
('Hammer'),
('Screwdriver'),
('Drill'),
('Broom'),
('Mop'),
('Vacuum Cleaner'),
('Desk Lamp'),
('Chair'),
('Table'),
('Blanket'),
('Pillow'),
('Towel'),
('Curtains'),
('Mirror'),
('Plant Pot'),
('Candles'),
('Clock'),
('Wall Art'),
('TV'),
('Laptop'),
('Smartphone'),
('Headphones'),
('Charger'),
('USB Cable'),
('Router'),
('Keyboard'),
('Mouse')
)
select abs(random() % 24) + 1 AS store_id, nom, abs(random() % 100) + 1 AS unitats from llistat;